### PR TITLE
Web Builder files

### PR DESCRIPTION
**Pull request by terjeio**
Initial web Builder files, currently only for the reference board. I'll link to these if/when merged.

### CODE REVIEW

**Comment by dresco** [comment]
Thanks Terje, very nice.

A couple of questions/observations;
- Features I've not tested yet (EEPROM for example), do I set those to 0 in the capabilities (or remove?) to mask them from the generator?
- RTC_ENABLE will need to be board specific (no 32.768 crystal on the SKR3), assuming I just move that from symbols to board specific build_flags? 
- There's some references to F756, I'll update those and add the other H7 supported boards.

Maybe an idea to put the binary in a zip with a text file of the selected build options? And perhaps provide a way to see the generated platformio build config (for developers)?

**Comment by terjeio** [comment]
> Features I've not tested yet (EEPROM for example), do I set those to 0 in the capabilities (or remove?) to mask them from the generator?

You can remove features completely by deleting them from the plugins array. In addition some are dependent on resources in the driver such as number of aux pins, i2c availability etc. More work is needed to handle this, e.g. when plugins are added so that the sum of aux pins required are greater than the number available. Complicated stuff, live update of resource usage may help...

> RTC_ENABLE will need to be board specific

It is when defined per board in the "boards" array, symbols defined in the root are common for all boards.
Note that root "caps" and board "caps" are merged before referenced, board "caps" has priority. Root "caps" is used for building the UI, the merged caps for enabling elements - the idea behind this is to let the user quickly compare boards.

> Maybe an idea to put the binary in a zip with a text file of the selected build options? 

I have many ideas yet to be implemented...
The ESP32 driver is already zipped because it contains 3 binaries - so easy to add, perhaps as an option.
My plan is to allow the user to save the choices for later builds.
How to flash instructions is needed as well - I have to decide how and where.

> And perhaps provide a way to see the generated platformio build config (for developers)?

Another option to be added to the UI?
Here is an example along with the latest .tpl file - I have added a section for ethernet to reduce build time. Most of the plugins has the code commented out so no big penalty for always including those.

[job.zip](https://github.com/dresco/STM32H7xx/files/9844235/job.zip)

If you want I can update the PR with the latest .tpl before you merge. Or just use the files and close without merging.

**Comment by dresco** [comment]
> If you want I can update the PR with the latest .tpl before you merge.

Cool, yes please then. And I'll get it merged & add the other boards..

Btw, the SDcard breakout was picked up today, so will hopefully be with you in a week or so.

**Comment by terjeio** [comment]
Use http://svn.io-engineering.com:8080/?dev=true to get the _.ini_ file along with the binary in a zip. I'll sort out how to add any compiler errors later.

**Comment by dresco** [comment]
Thanks Terje, I've merged and also updated for the BTT & WeAct boards. Fingers crossed..

**Comment by terjeio** [comment]
Here are the Web Builder files:

[Builder.zip](https://github.com/dresco/STM32H7xx/files/9853095/Builder.zip)

If you want read access to the subversion repo email me: terjeio@online.no
Since the builder is very much work in progress you may want that to stay up to date...

**Comment by dresco** [comment]
> Here are the Web Builder files
> If you want read access to the subversion repo email me

That's great thanks, will verify I can get up & running with the zipped version first.. :+1:

**Pull request merged**
